In [1]:
import numpy as np

In [3]:
np.array([4,5,6,3,6,7,8,8,9,4])

array([4, 5, 6, 3, 6, 7, 8, 8, 9, 4])

In [4]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [5]:
np.zeros(4)

array([0., 0., 0., 0.])

In [6]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [8]:
np.random.random()

0.23540699676358612

In [9]:
np.random.randint(1,10)

4

In [11]:
x = np.random.randint(1,100,24)

In [12]:
x

array([61, 35, 60, 90, 69, 65, 91, 74, 55, 41, 73, 18,  2, 19, 44, 19, 22,
       57, 21, 22, 56, 81, 47, 51])

In [13]:
x.shape

(24,)

In [15]:
x.reshape((4,6))

array([[61, 35, 60, 90, 69, 65],
       [91, 74, 55, 41, 73, 18],
       [ 2, 19, 44, 19, 22, 57],
       [21, 22, 56, 81, 47, 51]])

In [16]:
x.reshape((4,-1))

array([[61, 35, 60, 90, 69, 65],
       [91, 74, 55, 41, 73, 18],
       [ 2, 19, 44, 19, 22, 57],
       [21, 22, 56, 81, 47, 51]])

In [17]:
x.reshape((-1,4))

array([[61, 35, 60, 90],
       [69, 65, 91, 74],
       [55, 41, 73, 18],
       [ 2, 19, 44, 19],
       [22, 57, 21, 22],
       [56, 81, 47, 51]])

In [18]:
y = x.reshape((-1,4))

In [20]:
y.flatten()

array([61, 35, 60, 90, 69, 65, 91, 74, 55, 41, 73, 18,  2, 19, 44, 19, 22,
       57, 21, 22, 56, 81, 47, 51])

In [21]:
y = y.flatten()

In [22]:
np.sum(y)

1173

In [23]:
np.mean(y)

48.875

In [24]:
np.median(y)

53.0

In [25]:
np.std(y)

24.362389900555048

In [26]:
np.var(y)

593.5260416666666

In [28]:
x = x.reshape((-1,4))

In [29]:
x

array([[61, 35, 60, 90],
       [69, 65, 91, 74],
       [55, 41, 73, 18],
       [ 2, 19, 44, 19],
       [22, 57, 21, 22],
       [56, 81, 47, 51]])

In [31]:
np.sum(x,axis=1)

array([246, 299, 187,  84, 122, 235])

In [32]:
np.sum(x,axis=0)

array([265, 298, 336, 274])

In [33]:
np.mean(x, axis=0)

array([44.16666667, 49.66666667, 56.        , 45.66666667])